/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../styles/components/treatment-modal.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/treatment/treatment-utils`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-treatment-modal-logic`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/treatments` | `/treatments`; params?: Router.UnknownInputParams; } | { pathname: `/medication/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../styles/components/treatment-modal.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/treatment/treatment-utils`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/use-treatment-modal-logic`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/treatments` | `/treatments`; params?: Router.UnknownOutputParams; } | { pathname: `/medication/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../styles/components/treatment-modal.styles${`?${string}` | `#${string}` | ''}` | `/../components/treatment/treatment-utils${`?${string}` | `#${string}` | ''}` | `/../hooks/use-treatment-modal-logic${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/treatments${`?${string}` | `#${string}` | ''}` | `/treatments${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../styles/components/treatment-modal.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/treatment/treatment-utils`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-treatment-modal-logic`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/treatments` | `/treatments`; params?: Router.UnknownInputParams; } | `/medication/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/medication/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
